# TransCausNet: Transformer-Based DAG Aggregation for Scalable Causal Discovery

[![Python](https://img.shields.io/badge/Python-3.10+-blue.svg)]()
[![PyTorch](https://img.shields.io/badge/PyTorch-2.x-red.svg)]()
[![License](https://img.shields.io/badge/License-MIT-green.svg)]()

## Overview

TransCausNet (TCN) is a Transformer-based framework for scalable causal structure learning in high-dimensional settings.

Unlike traditional causal discovery approaches that attempt to learn a single global Directed Acyclic Graph (DAG), TransCausNet follows a **divide-and-conquer strategy**:

1. Decompose the global causal discovery problem into multiple local subspaces.
2. Generate diverse candidate DAGs using causal discovery algorithms such as:
   - DAGMA
   - NOTEARS
   - PC
   - GES
   - KDB
3. Integrate candidate structures using a Transformer-based aggregation network.
4. Enforce DAG validity through differentiable acyclicity regularization.
5. Produce a globally consistent causal graph.

The key idea is to **learn how to aggregate multiple causal hypotheses**, rather than selecting a single candidate graph.

---

### Pipeline

```text
Dataset
   │
   ▼
Subspace Decomposition
   │
   ├── Candidate DAG 1
   ├── Candidate DAG 2
   ├── Candidate DAG 3
   └── ...
   │
   ▼
Transformer-Based Aggregation
   │
   ├── Masked Multi-Head Attention
   ├── Adaptive Head Gating
   └── DAG Regularization
   │
   ▼
Global Causal Graph
```

---

## Features

- Transformer-based DAG aggregation
- Multi-head causal attention
- Adaptive candidate weighting
- Differentiable acyclicity constraint
- Sparse graph regularization
- Scalable divide-and-conquer learning
- Support for multiple causal discovery backends
- Suitable for distributed and federated causal learning

---

## Methodology

### Candidate Generation

TransCausNet can incorporate DAG candidates generated by:

| Method | Type |
|----------|----------|
| PC | Constraint-based |
| GES | Score-based |
| NOTEARS | Continuous Optimization |
| DAGMA | Continuous Optimization |
| KDB | Bayesian Structure Learning |

Each method generates local causal hypotheses that serve as attention masks for the Transformer.

---

### Transformer Aggregation

For each candidate DAG:

```math
A_h = softmax\left(
\frac{Q_h K_h^T}{\sqrt{d_k}}
+ \log(M_h + \epsilon)
\right)
```

where:

- \(M_h\) is the candidate DAG mask
- \(A_h\) is the head-specific adjacency estimate

The final graph is obtained by:

```math
A = \sum_{h=1}^{H} w_h A_h
```

where \(w_h\) are learnable reliability weights.

---

### Loss Function

```math
L =
L_{rec}
+
\lambda_c L_{causal}
+
\lambda_d L_{dag}
+
\lambda_{L1} L_{sparse}
```

Components:

- Reconstruction Loss
- Causal Directionality Loss
- DAG Constraint
- Sparsity Regularization

---

## Installation

Clone the repository:

```bash
git clone https://github.com/TransCausNet/TCN.git
cd TCN
```

Create environment:

```bash
conda create -n transcausnet python=3.10
conda activate transcausnet
```

Install dependencies:

```bash
pip install -r requirements.txt
```

---

## Usage

### Train TransCausNet

```bash
python train.py \
    --dataset sachs \
    --generator dagma \
    --heads 5 \
    --epochs 300
```

### Evaluate

```bash
python evaluate.py \
    --dataset sachs \
    --checkpoint checkpoints/best.pt
```

---

## Supported Datasets

| Dataset | Nodes |
|----------|----------|
| Asia | 8 |
| C-Suite | 9 |
| Sachs | 11 |
| Child | 20 |
| ALARM | 37 |
| Barley | 48 |
| Hailfinder | 56 |
| Andes | 223 |
| Diabetes | 413 |
| Link | 724 |

---

## Experimental Results

### Average F1 Score Improvement

| Generator | Best Candidate | TransCausNet |
|------------|---------------|--------------|
| PC | 0.4192 | **0.4490** |
| GES | 0.3829 | **0.4455** |
| NOTEARS | 0.3913 | **0.4250** |
| DAGMA | 0.4212 | **0.4478** |
| KDB | 0.4161 | **0.4682** |

Results show consistent improvements over individual candidate DAGs through attention-based integration.

---

## Why TransCausNet?

Traditional approaches:

```text
Data
  ↓
Learn One DAG
  ↓
Output
```

TransCausNet:

```text
Data
  ↓
Generate Multiple DAGs
  ↓
Learn Which Ones To Trust
  ↓
Aggregate Through Transformer
  ↓
Better Global DAG
```

This provides:

- Higher robustness
- Better scalability
- Lower SHD
- Improved F1 score
- Better handling of noisy candidate graphs

---

## Future Work

- Federated Causal Discovery
- Privacy-Preserving Graph Aggregation
- Dynamic Causal Graph Learning
- Temporal Causal Discovery
- Adaptive Subspace Partitioning
- Large-Scale Distributed Causal Learning

---






## License

This project is released under the MIT License.
